apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-world
  name: hello-world
spec:
  ports:
  - name: 5678-8000
    port: 5678
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello-world
  type: NodePort
status:
  loadBalancer: {}
